

INCLUDES = -I ..\include  -I..\..\qlinc\\

OBJS= entry.o transport.o events.o utils.o mgpio.o files.o global.o websrv.o socket.o calendar.o scheduler.o


all:listobj $(OBJS)


include ..\makefiledef
